<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
          <TargetFramework>net8.0-windows</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5.1" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Braver.Core\Braver.Core.csproj" />
  </ItemGroup>

</Project>
